### ISSUE TITLE
Add Trunk integration

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/sqlfmt-docs#10]
A community member contributed this integration:

https://github.com/trunk-io/plugins/pull/37

Need to add an integration page and maybe mention it in the tools list on the homepage.

**Comment by sxlijin** [comment]
We're happy to put together an integration page for you!

Some other things that Trunk brings to the table:

* we can run formatters in both pre-commit and pre-push
* we have a VSCode extension that can format-on-save
* we have CI integrations (e.g. GitHub Actions) that make it easy for folks to enforce formatting at CI time

As you've noticed from our trunk.yaml, our versioning logic makes it easy for users to version + install linters, and in addition, we also tell users when upgrades are available.

```
$ trunk check
++ 2022-11-03T13:07:00-0700 ++ trunk check

✔ No changes on your branch
Run trunk upgrade to upgrade trunk and 15 linters
```

**Comment by tconbeer** [comment]
That would be awesome, thank you!

**Comment by tconbeer** [comment]
A sqlfmt and Trunk user, @f-tremblay, added some instructions for the VS Code extension in an issue in the sqlfmt repo: https://github.com/tconbeer/sqlfmt/issues/306
